In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.7.0


In [2]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")


TensorFlow **IS** using the GPU


2021-12-29 09:15:06.648348: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 09:15:07.179977: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 09:15:07.181075: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


In [3]:
# Initializing a tensor

x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


2021-12-29 09:15:11.685762: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-29 09:15:11.687495: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 09:15:11.688107: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 09:15:11.688691: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zer

In [4]:
# Matrix Multiplication with Identity Matrix

# `tf.matmul()` and `@` are equivalent

print(tf.eye(x.shape[0], x.shape[0]) @ x)
print(tf.matmul(x,tf.eye(x.shape[1], x.shape[1])))


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [5]:
# Scalar Multiplication

5*x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [17]:
# Transpose

tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [24]:
#Softmax

tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [25]:
# Sum of items

tf.reduce_sum(tf.nn.softmax(x, axis=-1))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [34]:
# Reshape

tf.reshape(x, [1,6])

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6.]], dtype=float32)>

In [38]:
# Gives index of highest value

tf.argmax(x, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [28]:
# Tensors (as seen above) are constant

# x.assign([[2,3,4],[5,6,7]]) # <- This will not work 

var = tf.Variable([0.0, 0.0, 0.0])
var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [41]:
# Assigns a new value, adds and subs

var.assign([1,1,1])
var.assign_add([2,2,2])
var.assign_sub([0.5,0.5,0.5])
var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2.5, 2.5, 2.5], dtype=float32)>

In [39]:
#Converts to tensor

tf.convert_to_tensor(var)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.5, 2.5, 2.5], dtype=float32)>